
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GE = 36;
  public static final int UMINUS = 3;
  public static final int SEMI = 4;
  public static final int INT = 6;
  public static final int MINUS = 28;
  public static final int WRITE = 25;
  public static final int NOT = 39;
  public static final int AND = 37;
  public static final int LT = 33;
  public static final int RPAR = 12;
  public static final int OR = 38;
  public static final int BOOL = 9;
  public static final int COMMA = 5;
  public static final int FI = 19;
  public static final int DIV = 30;
  public static final int FLOAT_CONST = 45;
  public static final int PLUS = 27;
  public static final int ASSIGN = 26;
  public static final int IF = 16;
  public static final int ID = 43;
  public static final int LE = 34;
  public static final int EOF = 0;
  public static final int OD = 23;
  public static final int RETURN = 2;
  public static final int INT_CONST = 44;
  public static final int TRUE = 41;
  public static final int error = 1;
  public static final int NULL = 40;
  public static final int VOID = 15;
  public static final int EQ = 31;
  public static final int TIMES = 29;
  public static final int COLON = 13;
  public static final int ELSE = 20;
  public static final int READ = 24;
  public static final int CORP = 14;
  public static final int WHILE = 21;
  public static final int FLOAT = 8;
  public static final int THEN = 17;
  public static final int NE = 32;
  public static final int LPAR = 11;
  public static final int PROC = 10;
  public static final int STRING = 7;
  public static final int FALSE = 42;
  public static final int STRING_CONST = 46;
  public static final int GT = 35;
  public static final int ELIF = 18;
  public static final int DO = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RETURN",
  "UMINUS",
  "SEMI",
  "COMMA",
  "INT",
  "STRING",
  "FLOAT",
  "BOOL",
  "PROC",
  "LPAR",
  "RPAR",
  "COLON",
  "CORP",
  "VOID",
  "IF",
  "THEN",
  "ELIF",
  "FI",
  "ELSE",
  "WHILE",
  "DO",
  "OD",
  "READ",
  "WRITE",
  "ASSIGN",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "EQ",
  "NE",
  "LT",
  "LE",
  "GT",
  "GE",
  "AND",
  "OR",
  "NOT",
  "NULL",
  "TRUE",
  "FALSE",
  "ID",
  "INT_CONST",
  "FLOAT_CONST",
  "STRING_CONST"
  };
}

