// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: srcjflexcup/toy.flex

import java_cup.runtime.Symbol;
import java.util.HashMap;
import java.io.*;
import exception.FatalError;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class Yylex implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\2\2\22\0\1\1\1\4"+
    "\1\5\3\0\1\6\1\0\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\11\20\1\21\1\22"+
    "\1\23\1\24\1\25\2\0\32\26\4\0\1\26\1\0"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\2\26\1\40\1\26\1\41\1\42\1\43\1\26"+
    "\1\44\1\45\1\46\1\47\1\50\1\51\3\26\1\0"+
    "\1\52\10\0\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\1\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\2\14\1\15\1\16"+
    "\1\17\1\20\1\21\17\22\1\1\1\0\1\23\1\24"+
    "\1\0\1\2\1\0\1\25\1\26\1\27\1\30\2\22"+
    "\1\31\2\22\1\32\1\22\1\33\2\22\1\34\10\22"+
    "\1\35\1\36\2\37\1\40\6\22\1\41\11\22\2\0"+
    "\1\42\1\43\1\44\1\45\2\22\1\46\1\47\2\22"+
    "\1\50\1\51\1\52\2\22\1\53\1\54\2\22\1\55"+
    "\1\56\1\57\1\60";

  private static int [] zzUnpackAction() {
    int [] result = new int[111];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\53\0\53\0\53\0\126\0\201\0\53\0\53"+
    "\0\53\0\53\0\53\0\254\0\327\0\u0102\0\u012d\0\u0158"+
    "\0\53\0\u0183\0\53\0\u01ae\0\u01d9\0\u0204\0\u022f\0\u025a"+
    "\0\u0285\0\u02b0\0\u02db\0\u0306\0\u0331\0\u035c\0\u0387\0\u03b2"+
    "\0\u03dd\0\u0408\0\u0433\0\u045e\0\u0489\0\53\0\53\0\u04b4"+
    "\0\u04df\0\u050a\0\53\0\53\0\53\0\53\0\u0535\0\u0560"+
    "\0\u01d9\0\u058b\0\u05b6\0\u01d9\0\u05e1\0\u01d9\0\u060c\0\u0637"+
    "\0\u01d9\0\u0662\0\u068d\0\u06b8\0\u06e3\0\u070e\0\u0739\0\u0764"+
    "\0\u078f\0\53\0\53\0\u07ba\0\u07e5\0\u050a\0\u0810\0\u083b"+
    "\0\u0866\0\u0891\0\u08bc\0\u08e7\0\u01d9\0\u0912\0\u093d\0\u0968"+
    "\0\u0993\0\u09be\0\u09e9\0\u0a14\0\u0a3f\0\u0a6a\0\u07ba\0\u07e5"+
    "\0\u01d9\0\u01d9\0\u01d9\0\u01d9\0\u0a95\0\u0ac0\0\u01d9\0\u01d9"+
    "\0\u0aeb\0\u0b16\0\u01d9\0\u01d9\0\u01d9\0\u0b41\0\u0b6c\0\u01d9"+
    "\0\u01d9\0\u0b97\0\u0bc2\0\u01d9\0\u01d9\0\u01d9\0\u01d9";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[111];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\2\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\2\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\2\25\1\26\1\27"+
    "\1\30\1\31\1\32\2\25\1\33\1\25\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\25\1\42\1\43\1\44"+
    "\53\0\2\45\2\0\47\45\6\0\1\46\71\0\1\47"+
    "\36\0\1\50\4\0\1\51\51\0\1\52\52\0\1\52"+
    "\1\0\2\17\56\0\1\53\52\0\1\54\1\55\51\0"+
    "\1\56\45\0\2\25\5\0\24\25\20\0\2\25\5\0"+
    "\14\25\1\57\7\25\20\0\2\25\5\0\14\25\1\60"+
    "\7\25\20\0\2\25\5\0\14\25\1\61\7\25\20\0"+
    "\2\25\5\0\12\25\1\62\11\25\20\0\2\25\5\0"+
    "\1\25\1\63\7\25\1\64\1\65\11\25\20\0\2\25"+
    "\5\0\6\25\1\66\4\25\1\67\10\25\20\0\2\25"+
    "\5\0\21\25\1\70\2\25\20\0\2\25\5\0\4\25"+
    "\1\71\17\25\20\0\2\25\5\0\16\25\1\72\5\25"+
    "\20\0\2\25\5\0\5\25\1\73\16\25\20\0\2\25"+
    "\5\0\20\25\1\74\3\25\20\0\2\25\5\0\10\25"+
    "\1\75\5\25\1\76\5\25\20\0\2\25\5\0\14\25"+
    "\1\77\7\25\20\0\2\25\5\0\10\25\1\100\5\25"+
    "\1\101\5\25\53\0\1\102\5\45\1\103\45\45\11\104"+
    "\1\105\41\104\2\51\2\0\47\51\17\0\1\52\1\106"+
    "\51\0\2\25\5\0\14\25\1\107\7\25\20\0\2\25"+
    "\5\0\16\25\1\110\5\25\20\0\2\25\5\0\11\25"+
    "\1\111\5\25\1\112\4\25\20\0\2\25\5\0\12\25"+
    "\1\113\11\25\20\0\2\25\5\0\14\25\1\114\7\25"+
    "\20\0\2\25\5\0\20\25\1\115\3\25\20\0\2\25"+
    "\5\0\12\25\1\116\11\25\20\0\2\25\5\0\14\25"+
    "\1\117\7\25\20\0\2\25\5\0\1\25\1\120\22\25"+
    "\20\0\2\25\5\0\16\25\1\121\5\25\20\0\2\25"+
    "\5\0\5\25\1\122\16\25\20\0\2\25\5\0\21\25"+
    "\1\123\2\25\20\0\2\25\5\0\11\25\1\124\12\25"+
    "\20\0\2\25\5\0\11\25\1\125\12\25\20\0\2\25"+
    "\5\0\11\25\1\126\12\25\1\0\11\127\1\130\52\127"+
    "\1\130\4\127\1\3\34\127\17\0\2\25\5\0\12\25"+
    "\1\131\11\25\20\0\2\25\5\0\15\25\1\132\6\25"+
    "\20\0\2\25\5\0\6\25\1\133\15\25\20\0\2\25"+
    "\5\0\5\25\1\134\16\25\20\0\2\25\5\0\17\25"+
    "\1\135\4\25\20\0\2\25\5\0\1\25\1\136\22\25"+
    "\20\0\2\25\5\0\12\25\1\137\11\25\20\0\2\25"+
    "\5\0\3\25\1\140\20\25\20\0\2\25\5\0\4\25"+
    "\1\141\17\25\20\0\2\25\5\0\11\25\1\142\12\25"+
    "\20\0\2\25\5\0\13\25\1\143\10\25\20\0\2\25"+
    "\5\0\5\25\1\144\16\25\20\0\2\25\5\0\4\25"+
    "\1\145\17\25\20\0\2\25\5\0\12\25\1\146\11\25"+
    "\20\0\2\25\5\0\20\25\1\147\3\25\20\0\2\25"+
    "\5\0\5\25\1\150\16\25\20\0\2\25\5\0\20\25"+
    "\1\151\3\25\20\0\2\25\5\0\12\25\1\152\11\25"+
    "\20\0\2\25\5\0\13\25\1\153\10\25\20\0\2\25"+
    "\5\0\5\25\1\154\16\25\20\0\2\25\5\0\5\25"+
    "\1\155\16\25\20\0\2\25\5\0\13\25\1\156\10\25"+
    "\20\0\2\25\5\0\7\25\1\157\14\25\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3053];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\3\11\2\1\5\11\5\1\1\11\1\1\1\11"+
    "\21\1\1\0\2\11\1\0\1\1\1\0\4\11\23\1"+
    "\2\11\23\1\2\0\27\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[111];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    private HashMap<String, Symbol> symbolTable;
  /**
   * Creates a new scanner with symbol table inizialization.
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   * @param   inizialize  is @true if the symbolTable must be inizialized, @false otherwise
   */
    public Yylex(java.io.Reader in,  boolean inizialize) {
        this.zzReader = in;
        if(inizialize)
            symbolTable = new HashMap<String, Symbol> ();
    }

    public void cleanSymbolTable() throws IOException{
        symbolTable = new HashMap<String, Symbol> ();
    }

    private Symbol installID(String lexeme){
        Symbol symbol =  new Symbol (sym.ID, lexeme);
        symbolTable.put(lexeme, symbol);
        return symbol;
	}

	public HashMap<String, Symbol> getSymbolTable(){

		return symbolTable;
	}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Yylex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                return new Symbol(sym.EOF);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.err.println("Errore Lessicale: carattere illegale <" + yytext() + "> sulla linea:colonna -> " + (yyline + 1) + ":" + (yycolumn + 1 + "."));
            System.exit(1);
            }
            // fall through
          case 49: break;
          case 2:
            { /* ignore */
            }
            // fall through
          case 50: break;
          case 3:
            { return new Symbol(sym.NOT);
            }
            // fall through
          case 51: break;
          case 4:
            { try { throw new FatalError("Costante Stringa non chiusa"); } catch (FatalError e) { e. printStackTrace(); System.exit(1); }
            }
            // fall through
          case 52: break;
          case 5:
            { return new Symbol(sym.LPAR);
            }
            // fall through
          case 53: break;
          case 6:
            { return new Symbol(sym.RPAR);
            }
            // fall through
          case 54: break;
          case 7:
            { return new Symbol(sym.TIMES);
            }
            // fall through
          case 55: break;
          case 8:
            { return new Symbol(sym.PLUS);
            }
            // fall through
          case 56: break;
          case 9:
            { return new Symbol(sym.COMMA);
            }
            // fall through
          case 57: break;
          case 10:
            { return new Symbol(sym.MINUS);
            }
            // fall through
          case 58: break;
          case 11:
            { return new Symbol(sym.DIV);
            }
            // fall through
          case 59: break;
          case 12:
            { return new Symbol(sym.INT_CONST, yytext());
            }
            // fall through
          case 60: break;
          case 13:
            { return new Symbol(sym.COLON);
            }
            // fall through
          case 61: break;
          case 14:
            { return new Symbol(sym.SEMI);
            }
            // fall through
          case 62: break;
          case 15:
            { return new Symbol(sym.LT);
            }
            // fall through
          case 63: break;
          case 16:
            { return new Symbol(sym.EQ);
            }
            // fall through
          case 64: break;
          case 17:
            { return new Symbol(sym.GT);
            }
            // fall through
          case 65: break;
          case 18:
            { return this.installID(yytext());
            }
            // fall through
          case 66: break;
          case 19:
            { return new Symbol(sym.AND);
            }
            // fall through
          case 67: break;
          case 20:
            { return new Symbol(sym.RETURN);
            }
            // fall through
          case 68: break;
          case 21:
            { return new Symbol(sym.ASSIGN);
            }
            // fall through
          case 69: break;
          case 22:
            { return new Symbol(sym.LE);
            }
            // fall through
          case 70: break;
          case 23:
            { return new Symbol(sym.NE);
            }
            // fall through
          case 71: break;
          case 24:
            { return new Symbol(sym.GE);
            }
            // fall through
          case 72: break;
          case 25:
            { return new Symbol(sym.DO);
            }
            // fall through
          case 73: break;
          case 26:
            { return new Symbol(sym.FI);
            }
            // fall through
          case 74: break;
          case 27:
            { return new Symbol(sym.IF);
            }
            // fall through
          case 75: break;
          case 28:
            { return new Symbol(sym.OD);
            }
            // fall through
          case 76: break;
          case 29:
            { return new Symbol(sym.OR);
            }
            // fall through
          case 77: break;
          case 30:
            { return new Symbol(sym.STRING_CONST, yytext());
            }
            // fall through
          case 78: break;
          case 31:
            { try { throw new FatalError("Commento non chiuso"); } catch (FatalError e) { e. printStackTrace(); System.exit(1); }
            }
            // fall through
          case 79: break;
          case 32:
            { return new Symbol(sym.FLOAT_CONST, yytext());
            }
            // fall through
          case 80: break;
          case 33:
            { return new Symbol(sym.INT);
            }
            // fall through
          case 81: break;
          case 34:
            { return new Symbol(sym.BOOL);
            }
            // fall through
          case 82: break;
          case 35:
            { return new Symbol(sym.CORP);
            }
            // fall through
          case 83: break;
          case 36:
            { return new Symbol(sym.ELIF);
            }
            // fall through
          case 84: break;
          case 37:
            { return new Symbol(sym.ELSE);
            }
            // fall through
          case 85: break;
          case 38:
            { return new Symbol(sym.NULL);
            }
            // fall through
          case 86: break;
          case 39:
            { return new Symbol(sym.PROC);
            }
            // fall through
          case 87: break;
          case 40:
            { return new Symbol(sym.THEN);
            }
            // fall through
          case 88: break;
          case 41:
            { return new Symbol(sym.TRUE);
            }
            // fall through
          case 89: break;
          case 42:
            { return new Symbol(sym.VOID);
            }
            // fall through
          case 90: break;
          case 43:
            { return new Symbol(sym.FALSE);
            }
            // fall through
          case 91: break;
          case 44:
            { return new Symbol(sym.FLOAT);
            }
            // fall through
          case 92: break;
          case 45:
            { return new Symbol(sym.WHILE);
            }
            // fall through
          case 93: break;
          case 46:
            { return new Symbol(sym.WRITE);
            }
            // fall through
          case 94: break;
          case 47:
            { return new Symbol(sym.READ);
            }
            // fall through
          case 95: break;
          case 48:
            { return new Symbol(sym.STRING);
            }
            // fall through
          case 96: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
